# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  pull_request:
    branches: [ "development" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.head.sha }}
    
    - name: Use Node.js 20
      uses: actions/setup-node@v3
      with:
        node-version: 20
        cache: 'npm'
    - run: echo "Instalando dependencias"
    - run: npm ci
    - run: echo "Ejecutando build"
    - run: npm run build --if-present
    #- run: npm test

  #merge:
  #  runs-on: ubuntu-latest
  #  needs: build
  #  if: ${{ success() }}
  #  permissions:
  #    contents: write
  #    pull-requests: write
  #  steps:
  #    - name: Download source code
  #      uses: actions/checkout@v3
  #      with: 
  #        ref: ${{ github.base_ref }}
  #        fetch-depth: 0

  #    - name: Merge to development branches
  #      if: ${{ success() }}
  #      run: |
  #        git config --global user.email "EMAIL-OF-WORKFLOW@USER"
  #        git config --global user.name "WORKFLOW-USER"
  #        git merge --no-ff --verbose origin/${{ github.event.pull_request.head.ref }} -m "Merge pull request #${{ github.event.number }}"

  #    - name: Push changes after merge
  #      if: ${{ success() }}
  #      uses: ad-m/github-push-action@master
  #      with:
  #        github_token: ${{ secrets.GITHUB_TOKEN }}
  #        branch: ${{ github.base_ref }}